                                                                                        3. Review & Submit
                                                                                                </button>
                                                                                                      </div>

                                                                                                            <div className="tab-content">
                                                                                                                    {activeTabIndex === 0 && (
                                                                                                                              <div>
                                                                                                                                          <h2>Personal Information</h2>
                                                                                                                                                      <p>Content for Personal Info will go here.</p>
                                                                                                                                                                </div>
                                                                                                                                                                        )}

                                                                                                                                                                                {activeTabIndex === 1 && (
                                                                                                                                                                                          <div>
                                                                                                                                                                                                      <h2>Work Experience & Skills</h2>
                                                                                                                                                                                                                  <p>Content for Experience will go here.</p>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                            {activeTabIndex === 2 && (
                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                  <h2>Review Your Application</h2>
                                                                                                                                                                                                                                                                              <p>Content for Review & Submit will go here.</p>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                            <div className="tab-navigation">
                                                                                                                                                                                                                                                                                                                    <button onClick={onPrevious} disabled={isFirstTab}>
                                                                                                                                                                                                                                                                                                                              Previous
                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                              <button onClick={onNext} disabled={isLastTab}>
                                                                                                                                                                                                                                                                                                                                                        Next
                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                            export default Tabs;