
                                                                                                                            {/* Form for adding new todos */}
                                                                                                                                  <form onSubmit={handleSubmit} className="todo-form">
                                                                                                                                          <input
                                                                                                                                                    type="text"
                                                                                                                                                              value={newTodo}
                                                                                                                                                                        onChange={(e) => setNewTodo(e.target.value)}
                                                                                                                                                                                  placeholder="Add a new todo"
                                                                                                                                                                                          />
                                                                                                                                                                                                  <button type="submit">Add</button>
                                                                                                                                                                                                        </form>

                                                                                                                                                                                                              {/* Todo list display */}
                                                                                                                                                                                                                    {todos.length === 0 ? (
                                                                                                                                                                                                                            <p className="empty-message">No todos</p>
                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                          <ul className="todo-list">
                                                                                                                                                                                                                                                    {todos.map((todo) => (
                                                                                                                                                                                                                                                                <li
                                                                                                                                                                                                                                                                              key={todo.id}
                                                                                                                                                                                                                                                                                            className={`todo-item ${todo.completed ? 'completed' : ''}`}
                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                      type="checkbox"
                                                                                                                                                                                                                                                                                                                                                      checked={todo.completed}
                                                                                                                                                                                                                                                                                                                                                                      onChange={() => toggleComplete(todo.id)}
                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                  <span>{todo.text}</span>
                                                                                                                                                                                                                                                                                                                                                                                                              </li>
                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                            return (
                                                                                                                <div className="app">
                                                                                                                      <h1>Todo List</h1>
                                                                                                          };
                                                                          // Function to toggle the 'completed' status of a todo
                                                                            const toggleComplete = (id) => {
                                                                                setTodos(
                                                                                      todos.map((todo) =>
                                                                                              todo.id === id ? { ...todo, completed: !todo.completed } : todo
                                                                                                    )
                                                                                                        );

                                                                  // Clear the input field after adding
                                                                      setNewTodo('');
                                                                        };
